"""Tenant-scoped episodic reflections and repository adapters."""

from .context import (
    MAX_CONTEXT_FACTS,
    MAX_CONTEXT_PROCEDURES,
    ActiveProcedure,
    RepositoryReviewedMemoryReader,
    ReviewedMemoryContext,
    ReviewedMemoryReadPort,
)
from .contracts import (
    CompletionEvidence,
    FailureCode,
    ObservedFailure,
    RecoveryStep,
    ReflectionInputError,
    ReflectionRepository,
    ReflectionStorageError,
    ReflectionUsage,
    RepositoryClosedError,
    RunReflection,
    UnresolvedItem,
)
from .episodic import (
    InMemoryReflectionRepository,
    SQLiteReflectionRepository,
    reflect_run,
)
from .procedural import (
    InMemoryProcedureRepository,
    ProcedureAuthor,
    ProcedureRepository,
    ProcedureReview,
    ProcedureReviewState,
    ProcedureVersion,
    ProcedureVersionConflictError,
    SQLiteProcedureRepository,
)
from .semantic import (
    FactAuthor,
    FactConflictError,
    FactReview,
    FactReviewState,
    InMemorySemanticFactRepository,
    SemanticFact,
    SemanticFactRepository,
    SQLiteSemanticFactRepository,
)

__all__ = [
    "MAX_CONTEXT_FACTS",
    "MAX_CONTEXT_PROCEDURES",
    "ActiveProcedure",
    "CompletionEvidence",
    "FactAuthor",
    "FactConflictError",
    "FactReview",
    "FactReviewState",
    "FailureCode",
    "InMemoryProcedureRepository",
    "InMemoryReflectionRepository",
    "InMemorySemanticFactRepository",
    "ObservedFailure",
    "ProcedureAuthor",
    "ProcedureRepository",
    "ProcedureReview",
    "ProcedureReviewState",
    "ProcedureVersion",
    "ProcedureVersionConflictError",
    "RecoveryStep",
    "ReflectionInputError",
    "ReflectionRepository",
    "ReflectionStorageError",
    "ReflectionUsage",
    "RepositoryClosedError",
    "RepositoryReviewedMemoryReader",
    "ReviewedMemoryContext",
    "ReviewedMemoryReadPort",
    "RunReflection",
    "SQLiteProcedureRepository",
    "SQLiteReflectionRepository",
    "SQLiteSemanticFactRepository",
    "SemanticFact",
    "SemanticFactRepository",
    "UnresolvedItem",
    "reflect_run",
]
