"""Concrete tenant-scoped SQLite storage adapters."""

from .cloud import (
    CloudTask,
    CloudTaskAlreadyExistsError,
    CloudTaskClient,
    CloudTasksWorkQueue,
    DocumentStore,
    DocumentStoreTransaction,
    FirestoreEventRepository,
    FirestoreRunRepository,
    SignedWorkItemCodec,
    TaskDeliveryAuthError,
)
from .repositories import (
    ApiKeyHashRecord,
    ApiKeyScope,
    AuditEntry,
    SessionRecord,
    SQLiteAuditRepository,
    SQLiteEventRepository,
    SQLiteKeyHashRepository,
    SQLiteRunRepository,
    SQLiteSessionRepository,
    SQLiteTenantRepository,
    SQLiteWorkQueue,
    StorageConflictError,
    StorageError,
    TenantRecord,
    reflection_repository,
)
from .schema import MigrationError, migrate, validate_current_schema

__all__ = [
    "ApiKeyHashRecord",
    "ApiKeyScope",
    "AuditEntry",
    "CloudTask",
    "CloudTaskAlreadyExistsError",
    "CloudTaskClient",
    "CloudTasksWorkQueue",
    "DocumentStore",
    "DocumentStoreTransaction",
    "FirestoreEventRepository",
    "FirestoreRunRepository",
    "MigrationError",
    "SQLiteAuditRepository",
    "SQLiteEventRepository",
    "SQLiteKeyHashRepository",
    "SQLiteRunRepository",
    "SQLiteSessionRepository",
    "SQLiteTenantRepository",
    "SQLiteWorkQueue",
    "SessionRecord",
    "SignedWorkItemCodec",
    "StorageConflictError",
    "StorageError",
    "TaskDeliveryAuthError",
    "TenantRecord",
    "migrate",
    "reflection_repository",
    "validate_current_schema",
]
