"""Bounded research agent with validated evidence and citations."""

from .contracts import (
    Citation,
    EventType,
    ExtractedEvidence,
    FailureReason,
    OptionalAssistance,
    PublicEvent,
    QueryPlan,
    ScopedAnswer,
    SearchHit,
    SearchQuery,
    TerminalState,
    ToolBudget,
)
from .planning import (
    AssistancePolicy,
    PlanningDecision,
    PlanningPolicyError,
    QueryPlanner,
    TaskCategory,
)
from .providers import (
    FakeStructuredChatProvider,
    OllamaStructuredChatProvider,
    ProviderError,
    ProviderInvocation,
    ProviderMessage,
    ProviderMetadata,
    ProviderResponseError,
    ProviderResult,
    ProviderTimeoutError,
    StructuredChatProvider,
)
from .state import IllegalTransitionError, RunSnapshot, RunStateGraph, RunStatus

__all__ = [
    "AssistancePolicy",
    "Citation",
    "EventType",
    "ExtractedEvidence",
    "FailureReason",
    "FakeStructuredChatProvider",
    "IllegalTransitionError",
    "OllamaStructuredChatProvider",
    "OptionalAssistance",
    "PlanningDecision",
    "PlanningPolicyError",
    "ProviderError",
    "ProviderInvocation",
    "ProviderMessage",
    "ProviderMetadata",
    "ProviderResponseError",
    "ProviderResult",
    "ProviderTimeoutError",
    "PublicEvent",
    "QueryPlan",
    "QueryPlanner",
    "RunSnapshot",
    "RunStateGraph",
    "RunStatus",
    "ScopedAnswer",
    "SearchHit",
    "SearchQuery",
    "StructuredChatProvider",
    "TaskCategory",
    "TerminalState",
    "ToolBudget",
]
